Create RecursiveFibonacci.cpp
ReciHub/FunnyAlgorithms pull request #1009
Opened 2022-10-10 12:15 UTC by KORLA2

Now I have created a file have a look

2022-10-10 13:03 UTC, SaiSudhaV requested changes

2022-10-10 13:03 UTC, SaiSudhaV commented on Recursion/RecursiveFibonacci.cpp
> +    for(int i=3;i<=n;++i)
Add spaces before and after operators

2022-10-10 13:03 UTC, SaiSudhaV commented on Recursion/RecursiveFibonacci.cpp
> +    return fibonacci(n-1)+fibonacci(n-2);
Add spaces before and after operators

2022-10-10 13:03 UTC, SaiSudhaV commented on Recursion/RecursiveFibonacci.cpp
> +    cout<<" "<<fibonacci(i);
Add spaces before and after operators

2022-10-10 13:03 UTC, SaiSudhaV commented on Recursion/RecursiveFibonacci.cpp
> +    if(n==1)
Add spaces before and after operators

2022-10-10 13:03 UTC, SaiSudhaV commented on Recursion/RecursiveFibonacci.cpp
> +    if(n==2)return 1;
Add spaces before and after operators

2022-10-10 13:03 UTC, SaiSudhaV commented on Recursion/RecursiveFibonacci.cpp
> +    cout << "Fibonacci sequence: "<<n1<<" "<<n2;
Add spaces before and after operators

2022-10-10 14:06 UTC, KORLA2 commented
I have added spaces

2022-10-11 05:28 UTC, KORLA2 commented
I have changed

On Mon, 10 Oct 2022, 6:33 pm sai_sudha, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Recursion/RecursiveFibonacci.cpp
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1009#discussion_r991264560>
> :
>
> > +    if(n==2)return 1;
> +
> +    return fibonacci(n-1)+fibonacci(n-2);
> +}
> +
> +int main(){
> +
> + int n, n1 = 0, n2 = 1, n3 = 0;
> +
> +    cout << "Enter number: ";
> +
> +    cin >> n;
> +
> +    cout << "Fibonacci sequence: "<<n1<<" "<<n2;
> +
> +    for(int i=3;i<=n;++i)
>
> Add spaces before and after operators
> ------------------------------
>
> In Recursion/RecursiveFibonacci.cpp
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1009#discussion_r991264783>
> :
>
> > @@ -0,0 +1,32 @@
> +#include <iostream>
> +
> +
> +using namespace std;
> +
> +
> +int fibonacci(int n){
> +
> +    if(n==1)
> +      return 0;
> +
> +    if(n==2)return 1;
> +
> +    return fibonacci(n-1)+fibonacci(n-2);
>
> Add spaces before and after operators
> ------------------------------
>
> In Recursion/RecursiveFibonacci.cpp
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1009#discussion_r991264825>
> :
>
> > +    return fibonacci(n-1)+fibonacci(n-2);
> +}
> +
> +int main(){
> +
> + int n, n1 = 0, n2 = 1, n3 = 0;
> +
> +    cout << "Enter number: ";
> +
> +    cin >> n;
> +
> +    cout << "Fibonacci sequence: "<<n1<<" "<<n2;
> +
> +    for(int i=3;i<=n;++i)
> +
> +    cout<<" "<<fibonacci(i);
>
> Add spaces before and after operators
> ------------------------------
>
> In Recursion/RecursiveFibonacci.cpp
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1009#discussion_r991264886>
> :
>
> > @@ -0,0 +1,32 @@
> +#include <iostream>
> +
> +
> +using namespace std;
> +
> +
> +int fibonacci(int n){
> +
> +    if(n==1)
>
> Add spaces before and after operators
> ------------------------------
>
> In Recursion/RecursiveFibonacci.cpp
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1009#discussion_r991264992>
> :
>
> > @@ -0,0 +1,32 @@
> +#include <iostream>
> +
> +
> +using namespace std;
> +
> +
> +int fibonacci(int n){
> +
> +    if(n==1)
> +      return 0;
> +
> +    if(n==2)return 1;
>
> Add spaces before and after operators
> ------------------------------
>
> In Recursion/RecursiveFibonacci.cpp
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1009#discussion_r991265118>
> :
>
> > +      return 0;
> +
> +    if(n==2)return 1;
> +
> +    return fibonacci(n-1)+fibonacci(n-2);
> +}
> +
> +int main(){
> +
> + int n, n1 = 0, n2 = 1, n3 = 0;
> +
> +    cout << "Enter number: ";
> +
> +    cin >> n;
> +
> +    cout << "Fibonacci sequence: "<<n1<<" "<<n2;
>
> Add spaces before and after operators
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1009#pullrequestreview-1135984667>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXB7SLYRKEHSM4Y24W7XC2LWCQH23ANCNFSM6AAAAAARBJJ4RM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 06:16 UTC, SaiSudhaV approved these changes

2022-10-11 06:16 UTC, merged