Adding Kth Element Python Code
ReciHub/FunnyAlgorithms pull request #1010
Opened 2022-10-11 01:28 UTC by JVBravoo

2022-10-11 06:24 UTC, SaiSudhaV requested changes

2022-10-11 06:24 UTC, SaiSudhaV commented on Kth Element/smallest-Kth-element.py
> +    return arr[k-1]
Add spaces before and after operator

2022-10-11 06:26 UTC, SaiSudhaV commented
Hello @JVBravoo 
Thank you for contributing. Add the description for the PR and make necessary change(s) in the code.

2022-10-14 17:48 UTC, JVBravoo reviewed
Changes were made in the following commit: https://github.com/ReciHub/FunnyAlgorithms/pull/1010/commits/d65ea0cf84cae3416192079cab8a1be363d7f0ae

2022-10-25 20:44 UTC, merged