Create balancedparanthesis.js
ReciHub/FunnyAlgorithms pull request #1026
Opened 2022-10-14 10:55 UTC by KORLA2

Simple code to find wheather a paranthesis is balanced or not

2022-10-14 14:27 UTC, SaiSudhaV requested changes

2022-10-14 14:27 UTC, SaiSudhaV commented on Balanced Paranthesis/balancedparanthesis.js
> +
Here if and else should be enclosed inside a block or else you will get an exception saying else without a block.

2022-10-14 14:27 UTC, SaiSudhaV commented on Balanced Paranthesis/balancedparanthesis.js
> +let count=0;
Add spaces before and after operator

2022-10-14 14:27 UTC, SaiSudhaV commented on Balanced Paranthesis/balancedparanthesis.js
> +else count++;
Maintain indentation

2022-10-14 14:28 UTC, SaiSudhaV commented
Hello @KORLA2 
Please add the changes suggested. Code looks great just need to beautify it.

Thank you
Sudha

2022-10-14 15:54 UTC, KORLA2 commented
Hello I have changed have a look

2022-10-15 07:28 UTC, KORLA2 commented
Hello I have added spaces

On Fri, 14 Oct 2022, 7:58 pm sai_sudha, ***@***.***> wrote:

> Hello @KORLA2 <https://github.com/KORLA2>
> Please add the changes suggested. Code looks great just need to beautify
> it.
>
> Thank you
> Sudha
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1026#issuecomment-1279086850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXB7SL3CNESEQ3GDMZLQTE3WDFUZPANCNFSM6AAAAAARFD7MKM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-16 07:21 UTC, KORLA2 commented
Any updates on my PR

On Sat, 15 Oct 2022, 12:58 pm 19_531; GOUTHAM;, ***@***.***>
wrote:

> Hello I have added spaces
>
> On Fri, 14 Oct 2022, 7:58 pm sai_sudha, ***@***.***> wrote:
>
>> Hello @KORLA2 <https://github.com/KORLA2>
>> Please add the changes suggested. Code looks great just need to beautify
>> it.
>>
>> Thank you
>> Sudha
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ReciHub/FunnyAlgorithms/pull/1026#issuecomment-1279086850>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXB7SL3CNESEQ3GDMZLQTE3WDFUZPANCNFSM6AAAAAARFD7MKM>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-10-16 09:20 UTC, SaiSudhaV requested changes

2022-10-16 09:20 UTC, SaiSudhaV commented on Balanced Paranthesis/balancedparanthesis.js
> +
I mentioned to add to for block not for if and else. I have explained the cause for not enclosing for loop in block. Please add that.

2022-10-16 10:14 UTC, KORLA2 commented
Hello I have made changes

On Sun, 16 Oct 2022, 2:50 pm sai_sudha, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Balanced Paranthesis/balancedparanthesis.js
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1026#discussion_r996414964>
> :
>
> > @@ -0,0 +1,15 @@
> + function balanced_paranthesis( brackets ){
> +
> +let count=0;
> +
> +   for(let i = 0 ; i < brackets.length ; ++i)
> +
>
> I mentioned to add to for block not for if and else. I have explained the
> cause for not enclosing for loop in block. Please add that.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ReciHub/FunnyAlgorithms/pull/1026#pullrequestreview-1143272740>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXB7SLY3M4LX2BLDULDVX4LWDPCFZANCNFSM6AAAAAARFD7MKM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-16 11:16 UTC, SaiSudhaV approved these changes

2022-10-16 11:16 UTC, merged