Updated the PalindromeChecker java code
ReciHub/FunnyAlgorithms pull request #1028
Opened 2022-10-14 14:10 UTC by CodeXstalker

Hey @ReciHub ,
I added the optimized java code for Palindrome Number, please have a look.

2022-10-14 14:11 UTC, CodeXstalker commented
@ReciHub please have a look

2022-10-14 14:40 UTC, SaiSudhaV requested changes

2022-10-14 14:40 UTC, SaiSudhaV commented on PalindromeChecker/OptimizedPalindromeChecker.java
> +public boolean isPalindrome(int x) {
This code works for numbers but the previous is for strings. Please do add a new file instead modifying as these 2 are different functionalities.

2022-10-14 18:10 UTC, CodeXstalker commented on PalindromeChecker/OptimizedPalindromeChecker.java
> +public boolean isPalindrome(int x) {
@ReciHub , I request you to merge for the number, Coz it is best optimized for it.

2022-10-14 18:28 UTC, CodeXstalker commented
@ReciHub I added the algorithm for Prime Checker using Regular Expression in java.
So, Have a look and consider  it.

2022-10-16 11:18 UTC, SaiSudhaV approved these changes

2022-10-16 11:18 UTC, merged