Added longestWord in C++ language
ReciHub/FunnyAlgorithms pull request #1049
Opened 2022-10-16 15:49 UTC by sarita1124

- Added a c++ program to reads a string input and outputs the longest word int the given input.

2022-10-16 16:54 UTC, pathakharsh123 commented
please assign me this issue

2022-10-20 05:39 UTC, SaiSudhaV requested changes

2022-10-20 05:39 UTC, SaiSudhaV commented on longestWord/longestWord.cpp
> +	cout<<longest_word<<endl;
Add spaces before and after operators

2022-10-20 08:02 UTC, sarita1124 commented on longestWord/longestWord.cpp
> +	    if (input[i]==' ') {
Hey I have updated and made new commit. Please check.

2022-10-25 07:23 UTC, SaiSudhaV approved these changes

2022-10-25 07:23 UTC, merged