Added Bubble Sort Algorithm in Rust
ReciHub/FunnyAlgorithms pull request #1119
Opened 2022-11-15 13:25 UTC by Yujin-nKim

Hello, we are studying Rust language and want to contribute to your repo. This time, we implemented bubble sort in the Rust language and sent you a PR. Merge, please.😊

2022-11-30 15:34 UTC, Yujin-nKim commented
@Marcosschwaab  @marlonchalegre  @tricinel  @melko  Hello, we left a PR. I hope to be Merge soon. I am interested in this repo.😊

2022-12-02 16:37 UTC, Yujin-nKim commented
Hello. I additionally committed the code that implements the "happy number" algorithm in Rust. Please check and merge.

2022-12-06 18:01 UTC, Yujin-nKim commented
Hello. I additionally committed the code that implements the "Insertion sort" and "selection sort" algorithm in Rust. Please check and merge. @Marcosschwaab @marlonchalegre @tricinel @melko

2022-12-30 15:40 UTC, marlonchalegre requested changes
Delete unnecessary files

2022-12-30 15:40 UTC, marlonchalegre commented on HappyNumber/HappyNumber.rs
> +use std::io;
Where this file is used in the bubble sort solution?

2023-02-21 07:08 UTC, closed without merging