Added Poker Code
ReciHub/FunnyAlgorithms pull request #730
Opened 2020-10-03 06:47 UTC by shim1998

2020-10-23 14:33 UTC, CaioCordeiro commented
What a great code :smile: !
Just a little tip, its good to always put a description on your PRs to make more understandable.
Thank you for contributing! :rocket:
I just have a few remarks about your PR.
I would separate this PR into 2 PRs, one for the 'Poker Code' and other to the Cardiogram

2020-10-23 14:34 UTC, CaioCordeiro requested changes

2020-10-23 14:34 UTC, CaioCordeiro commented on Poker/poker.cpp
> +    // cout<<a<<' '<<b<<'\n';
I would remove this comment :smile:

2020-10-23 14:34 UTC, CaioCordeiro commented on Poker/poker.cpp
> +    // #endif
I would remove this comment smile :smile:

2020-10-24 07:32 UTC, shim1998 commented on Poker/poker.cpp
> +    // cout<<a<<' '<<b<<'\n';
Sure :D

2022-09-30 17:54 UTC, closed without merging