Add sum_of_numbers.js and reverse_integer.py
ReciHub/FunnyAlgorithms pull request #740
Opened 2020-10-05 17:12 UTC by dephraiim

2020-10-11 14:49 UTC, dephraiim commented
@OtacilioN

2020-10-23 14:59 UTC, CaioCordeiro commented
What a great code :smile: !
Just a little tip, its good to always put a description on your PRs to make more understandable.
Thank you for contributing! :rocket:
I would separate this PR in 3 PRs, one for the 'sum_of_numbers', other for the 'Strict equaling' fix and another for the 'reverse_integer' (I'll wait your response)

2022-09-30 17:58 UTC, CaioCordeiro requested changes

2022-09-30 17:58 UTC, CaioCordeiro commented on ReverseInteger/reverse_integer.py
> +print(reverse_integer(43455))
Please add an empty line in the end of the file.

2023-10-03 14:22 UTC, closed without merging

2023-10-03 14:22 UTC, OtacilioN commented
Closing due to inactivity, feel free to reopen.