Sliding Animated Form using HTML, CSS and JS
ReciHub/FunnyAlgorithms pull request #953
Opened 2022-10-02 10:46 UTC by Mridul2820

2022-10-02 13:37 UTC, CaioCordeiro requested changes
What a great code 😄 !
Just a little tip, it's good always to put a description on your PRs to make it more understandable. Could you add it for me?
Thank you for contributing! 🚀

2022-10-02 13:37 UTC, CaioCordeiro commented on sliding-form/index.html
> +</html>
Please add an empty line at the end of the file.

2022-10-02 13:37 UTC, CaioCordeiro commented on sliding-form/script.js
> +});
Here too.

2022-10-02 13:37 UTC, CaioCordeiro commented on sliding-form/style.scss
> +}
Also here.

2022-10-04 12:09 UTC, CaioCordeiro commented
@Mridul2820  Please add a description to your PR 😄 .
The code looks fantastic.

2022-10-04 12:35 UTC, Mridul2820 commented
Hi @CaioCordeiro I have added the description and also a screenshot of the page

2022-10-09 02:43 UTC, Mridul2820 commented
Hi @CaioCordeiro I have added all the changes you asked

2022-10-10 12:59 UTC, merged