Added ArrayReverse with cpp
ReciHub/FunnyAlgorithms pull request #999
Opened 2022-10-08 16:33 UTC by HariKrishnaShivs

Implemented ArrayReverse using C++ language

2022-10-11 06:21 UTC, SaiSudhaV requested changes

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +    for(int i=0;i<=(n/2)-1;i++)
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +    int n=v.size(),tmp;
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +        v[n-1-i]=v[i];
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +        v[i]=tmp;
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +        tmp=v[n-1-i];
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +    cout<<"Enter array size:"<<endl;
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +    cout<<"Enter "<<n<<" array values:"<<endl;
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +    for(int i=0;i<n;i++)
Add spaces before and after operator

2022-10-11 06:21 UTC, SaiSudhaV commented on ReverseArray-InPlace/ArrayReverse.cpp
> +    for(int i=0;i<n;i++)
Add spaces before and after operator

2022-10-11 06:22 UTC, SaiSudhaV commented
Hello @HariKrishnaShivs 
Thank you for contributing.
Add spaces before and after every operator in the code. Let me know once you are done with the changes.

2022-10-11 06:41 UTC, HariKrishnaShivs commented
Thanks for the review @SaiSudhaV . I've made the changes as requested in the latest commit. Please review it again.

2022-10-12 05:27 UTC, SaiSudhaV approved these changes

2022-10-12 05:28 UTC, SaiSudhaV commented
Thank You @HariKrishnaShivs. Go ahead with your contributions.

2022-10-12 05:28 UTC, merged